### ISSUE TITLE
20200115 caml_alloc_initialized_string

### ISSUE THREAD

**Issue by olafhering** [thierry-martinez/pyml#46]
The 20200115 release fails to compile with ocaml 4.04/4.05:
````
[   48s] ocamlfind ocamlc -c pyml_stubs.c -o pyml_stubs.o
[   48s] pyml_stubs.c: In function 'PyString_AsStringAndSize_wrapper':
[   48s] pyml_stubs.c:1267:18: warning: implicit declaration of function 'caml_alloc_initialized_string'; did you mean 'caml_alloc_string'? [-Wimplicit-function-declaration]
[   48s]          string = caml_alloc_initialized_string(length, buffer);         \
[   48s]                   ^
[   48s] pyml_stubs.c:1273:1: note: in expansion of macro 'StringAndSize_wrapper'
[   48s]  StringAndSize_wrapper(PyString_AsStringAndSize, char);
[   48s]  ^~~~~~~~~~~~~~~~~~~~~
````

**Comment by thierry-martinez** [comment]
Nice catch! This should be fixed now, with the upstream version of stdcompat ( https://github.com/thierry-martinez/stdcompat ). I will make a new release quite soon. Thanks!

**Comment by olafhering** [comment]
While the header is installed via stdcompat, pyml does not add the required `-I<path>` to the CFLAGS.

**Comment by thierry-martinez** [comment]
I noticed that afterwards, sorry for having missed that: it is now fixed. Thank you again!
